# ./github/workflows/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/prsk-cheering"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/prsk-dependabot"
    schedule:
      interval: "weekly"