# .github/workflows/lint.yml
name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check JSON syntax
        run: |
          files=$(git ls-files 'common/*.constants.json' 'prsk-*/*.constants.json')
          for f in $files; do
            echo "::group::$f"
            jq -e . "$f" > /dev/null
            echo "::endgroup::"
          done

      - name: Check JSON formatting
        run: npx --yes prettier@3 --check '{common,prsk-*}/*.constants.json'

  yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install yamllint
        run: pip install --user yamllint

      - name: Check YAML syntax
        run: yamllint .github/workflows/ .github/dependabot.yml prsk-*/action.yml
