# .github/workflows/prsk-cheering.yml
name: PR prsk cheering

on:
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  set-prsk-label-and-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set prsk label and comments
        uses: ./prsk-cheering
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}